Update H2MigrationUI.java - Use normal char instead of special char
If run gradlew in Windows exception happened with following message.

C:\Users\sam12\test\mvstore\H2MigrationTool\src\main\java\com\manticore\h2\H2MigrationUI.java:169: error: unmappable character (0xE2) for encoding x-windows-949
                                            textArea.append(e.getKey().getAbsolutePath() + " ?넂 "

I suggent use more normal charactor for various environment without any additional configuration.